params:
  seed: ${...seed}

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      # units: [256, 128, 64]
      units: [512, 512]
      activation: elu
      d2rl: False
      
      initializer:
        name: default
      regularizer:
        name: None
    rnn:
        name: lstm
        units: 1024
        layers: 1
        before_mlp: True
        layer_norm: True

  load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load

  config:
    name: ${resolve_default:Chair,${....experiment}}
    full_experiment_name: ${.name}
    env_name: rlgpu
    multi_gpu: ${....multi_gpu}
    ppo: True
    mixed_precision: False
    normalize_input: True
    normalize_value: True
    value_bootstrap: False
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.998
    tau: 0.95
    learning_rate: 1e-4 # 1e-10 # 3e-4
    lr_schedule: linear # adaptive
    schedule_type: standard # legacy
    kl_threshold: 0.01 # 0.008
    score_to_win: 20000
    max_epochs: ${resolve_default:500,${....max_iterations}}
    save_best_after: 200
    save_frequency: 50
    grad_norm: 1.0
    entropy_coef: 0.002 # 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 16
    minibatch_size: 16384 # 32768
    mini_epochs: 4
    critic_coef: 4 # 2
    clip_value: True
    seq_len: 16 # 4
    bounds_loss_coef: 0.005 # 0.0001
    zero_rnn_on_done: False
